function [E_down,BC_down,Bo,Co,E_up,BC_up] = Five_bar_position_rigid_foot(LA,LB,LC,LC1,LD,LN,qA,qD)
%Five_bar_position_rigid_foot
%    [E_down,BC_down,Bo,Co,E_up,BC_up] = Five_bar_position_rigid_foot(LA,LB,LC,LC1,LD,LN,qA,qD)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    31-May-2025 17:34:01

t2 = cos(qA);
t3 = cos(qD);
t4 = sin(qA);
t5 = sin(qD);
t6 = LA.^2;
t7 = LA.^3;
t8 = LB.^2;
t9 = LC1.^2;
t10 = LD.^2;
t11 = LD.^3;
t12 = LN.^2;
t13 = qA.*2.0;
t14 = qD.*2.0;
t25 = 1.0./LC1;
t26 = -qD;
t27 = LB.*LC1.*2.0;
t15 = t2.^2;
t16 = t3.^2;
t17 = sin(t13);
t18 = t4.^2;
t19 = sin(t14);
t20 = t5.^2;
t21 = LA.*t2;
t22 = LD.*t3;
t23 = LA.*t4;
t24 = LD.*t5;
t28 = -t6;
t29 = -t8;
t30 = -t9;
t31 = -t10;
t32 = -t12;
t35 = qA+t26;
t38 = t4.*t7;
t39 = t5.*t11;
t33 = -t21;
t34 = -t24;
t36 = LN.*t21.*2.0;
t37 = LN.*t22.*2.0;
t40 = cos(t35);
t41 = t8.*t23;
t44 = t9.*t24;
t49 = -t38;
t50 = -t39;
t51 = t23.*t30;
t52 = t24.*t29;
t53 = t23.*t32;
t54 = t24.*t32;
t55 = LN.*t6.*t17;
t59 = LN.*t22.*t23.*-2.0;
t63 = t10.*t20.*t23;
t64 = t6.*t18.*t24;
t65 = LN.*t19.*t31;
t68 = t2.*t4.*t6.*t22.*2.0;
t69 = t3.*t5.*t10.*t21.*2.0;
t72 = t16.*t23.*t31;
t73 = t15.*t24.*t28;
t47 = -t36;
t48 = -t37;
t57 = t24.*t36;
t62 = t23+t34;
t66 = LA.*LD.*t40.*2.0;
t67 = LN+t22+t33;
t75 = t8+t10+t12+t28+t30+t37;
t70 = -t66;
t71 = abs(t67);
t74 = 1.0./t67;
t83 = t8+t9+t27+t28+t31+t32+t36+t48+t66;
t76 = t6+t10+t12+t37+t47+t70;
t80 = (t74.*t75)./2.0;
t77 = abs(t76);
t78 = 1.0./t76;
t81 = -t80;
t82 = t27+t29+t30+t76;
t79 = 1.0./t77;
t84 = t82.*t83;
t85 = sqrt(t84);
t86 = t12.*t71.*t79.*t85;
t88 = t37.*t71.*t79.*t85;
t89 = LN.*t21.*t71.*t79.*t85.*-2.0;
t90 = t6.*t15.*t71.*t79.*t85;
t91 = t10.*t16.*t71.*t79.*t85;
t92 = t6.*t18.*t71.*t79.*t85;
t93 = t10.*t20.*t71.*t79.*t85;
t94 = t21.*t22.*t71.*t79.*t85.*2.0;
t95 = t23.*t24.*t71.*t79.*t85.*2.0;
t96 = -t94;
t97 = -t95;
t98 = t41+t44+t49+t50+t51+t52+t53+t54+t55+t57+t59+t63+t64+t65+t68+t69+t72+t73+t86+t88+t89+t90+t91+t92+t93+t96+t97;
t99 = (t78.*t98)./2.0;
t106 = t62.*t74.*t78.*t98.*(-1.0./2.0);
t100 = -t99;
t101 = t24+t99;
t105 = t62.*t74.*t99;
t107 = t80+t106;
t102 = LC.*t25.*t101;
t108 = LN+t22+t81+t105;
t103 = -t102;
t109 = LC.*t25.*t108;
t104 = t24+t103;
t110 = -t109;
t111 = LN+t22+t110;
E_down = [t111;t104];
if nargout > 1
    BC_down = [t107;t100];
end
if nargout > 2
    Bo = [t21;t23];
end
if nargout > 3
    Co = [LN+t22;t24];
end
if nargout > 4
    E_up = [t111;t104];
end
if nargout > 5
    BC_up = [t107;t100];
end
end
